{{- $fullName := .Chart.Name -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "hello-world-php.fullname" .}}
  labels:
    app.kubernetes.io/instance: {{ include "hello-world-php.fullname" .}}
    app.kubernetes.io/name: {{ include "hello-world-php.fullname" .}}
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "hello-world-php.fullname" .}}
    weight: 100
  tls:
    termination: edge  
  wildcardPolicy: None