apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
 name: hello-world-php-GitHub-listener-interceptor
spec:
 serviceAccountName: pipeline
 triggers:
   - name: GitHub-listener
     bindings:
       - ref: hello-world-php-pipeline-binding
     template:
       name: hello-world-trigger-pipeline-template