apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
 name: hello-world-php-pipeline-binding
spec:
 params:
 - name: gitrepositoryurl
   value: $(body.repository.html_url)
 - name: gitrevision
   value: $(body.ref)
 - name: releaseversion
   value: $(release_version)